---

- name: install Python dependencies
  apt: pkg={{ item }}  state=present
  with_items:
    - g++
    - make
    - libxslt-dev     # for python lxml package
    - python3
    - python3-pip
    - python3-dev
    - python3-setuptools
    - python3-pycurl
    - python3.4-venv
    # pillow dependencies
    - libjpeg-dev
    - libtiff4-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.5-dev
    - tk8.5-dev
    - gettext         # GNU gettext toolset for translations

- name: Update tools
  pip: name='setuptools pip' state=latest executable=/usr/bin/pip3

- name: Install global python packages
  pip: name='{{python_global_packages|join(" ")}}' executable=/usr/bin/pip3

- name: Setup virtualenvs
  shell: python3 -m venv {{ item.home }}/{{ item.name }}
  args:
    creates: '{{ item.home }}/{{ item.name }}'
  with_items: python_virtualenvs
  become: yes
  become_user: '{{ item.owner }}'

- name: setup activate environment settings
  lineinfile: dest={{ item.home }}/{{ item.name }}/bin/activate state=present line='export {{ item.env_key }}="{{ item.env_value }}"'
  with_items: virtualenv_activate_settings

- name: Activate virtualenv on shell login for each virtualenv
  lineinfile: dest={{ item.home }}/.bashrc state=present line="source {{ item.home }}/{{ item.name }}/bin/activate"
  with_items: python_virtualenvs
