# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.04/ubuntu-14.04-amd64.box"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../django-dev.yml"
    ansible.sudo = true
    ansible.extra_vars = "ansible-settings.yml"
  end
  config.vm.synced_folder ".", "/home/vagrant/my_app"
  config.vm.network "private_network", ip: "10.0.0.101"
  config.vm.network "forwarded_port", host: 5000, guest: 8000
  config.vm.network "forwarded_port", host: 8888, guest: 80
  config.vm.provider "virtualbox" do |v|
    v.name = "Django VM"
  end
end
