---

- name: Make OpenSSH secure(r)
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
  with_items:
    - { key: 'PermitRootLogin', value: 'no'}
    - { key: 'PasswordAuthentication', value: 'no'}
    - { key: 'X11Forwarding', value: 'no'}
  notify: restart ssh

- name: OpenSSH allow only very strong crypto
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
  with_items:
    - { key: 'Ciphers', value: 'aes256-ctr'}
    - { key: 'MACs', value: 'hmac-sha2-512'}
  notify: restart ssh


