---
# Jenkins doesn't allow updates via CLI, though that is required before plugins
# can be installed via CLI. See: https://gist.github.com/rowan-m/1026918
- name: Create Jenkins updates folder.
  file:
    path: /var/lib/jenkins/updates
    owner: jenkins
    group: jenkins
    mode: 0755
    state: directory

- name: Update Jenkins plugin data.
  shell: >
    curl -L https://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /var/lib/jenkins/updates/default.json
    creates=/var/lib/jenkins/updates/default.json

- name: Permissions for default.json updates info.
  file:
    path: /var/lib/jenkins/updates/default.json
    owner: jenkins
    group: jenkins
    mode: 0755

# Example from Ansible Playbooks
- name: Copy admin password file
  shell: >
    cat /var/lib/jenkins/secrets/initialAdminPassword > ~/p
  become: true

- name: Install Jenkins plugins.
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:8080/ install-plugin {{ item }} --username admin --password-file ~/p
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: jenkins_plugins
  become: true
  ignore_errors: yes
  notify: restart jenkins

# Pause for 5 minutes to build app cache.
- name: Pause 30 seconds
  pause: seconds=30

- name: Install Jenkins plugins (retry)
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:8080/ install-plugin {{ item }} --username admin --password-file ~/p
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: jenkins_plugins
  become: true
  notify: restart jenkins

- name: load first time Jenkins password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: result
  become: true

- name: Show Jenkins first time admin password
  debug: msg="{{ result.stdout }}"
