---

- name: install mpapis public key
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  sudo: no

- name: ruby install
  shell: \curl -sSL https://get.rvm.io | bash -s stable --ruby={{ ruby_ver }}
  args:
    creates: '{{ admin_user.home }}/.rvm/rubies/default/bin/ruby'
  sudo: no
